name: "Airport Checkin"

on:
  schedule:
    - cron: "0 22 * * *"  # 每天 UTC+22 运行 (北京时间 06:00)
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-100 -n 1)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run checkin (multi-account)
        env:
          SCKEY: ${{ secrets.SCKEY }}
          TOKEN: ${{ secrets.TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}|${{ secrets.EMAIL1 }}
          PASSWD: ${{ secrets.PASSWD }}|${{ secrets.PASSWD1 }}
        run: python3 ./main.py
